# frozen_string_literal: true

require "bundler/gem_tasks"

Bundler::GemHelper.tag_prefix = "bareruby-stdlib-"

require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: %i[spec rubocop]
